/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.skyjo;

/**
 *
 * @author Admin
 */
public class InstructionPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InstructionPage.class.getName());

    /**
     * Creates new form InstructionPage
     */
    public InstructionPage() {
        initComponents();
        jTextPane1.setContentType("text/html");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        closeButton = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 48)); // NOI18N
        jLabel1.setText("Rulebook");

        jButton1.setText("Objective");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Setup");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setText("Turn Structure");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setText("Hidden Cards");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton5.setText("Column Elimation");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("End of Round");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton8.setText("Scoring");
        jButton8.addActionListener(this::jButton8ActionPerformed);

        jButton9.setText("Game End");
        jButton9.addActionListener(this::jButton9ActionPerformed);

        jScrollPane2.setViewportView(jTextPane1);

        closeButton.setText("CLOSE");
        closeButton.addActionListener(this::closeButtonActionPerformed);

        jButton7.setText("Penalty Rule");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(closeButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(closeButton)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        new Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTextPane1.setText(
                "<html> "
                        + "<h3> Objective </h3>"
                        + "<ul>"
                        + "<li> Minimize your total score. </li>"
                        + "<li> The game ends when a player reaches 100 or more points at the end of a round. </li>"
                        + "<li> The player with the lowest total score wins. </li>"
                        + "</ul>"
                        + "</html>");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextPane1.setText(
                "<html> "
                        + "<h3> Setup </h3>"
                        + "<ul>"
                        + "<li> 2-4 players. </li>"
                        + "<li> Each player has a grid of 12 face down cards. </li>"
                        + "<li> The grid is arranged with 4 columns and 3 rows. </li>"
                        + "<li> The draw deck consists of all remaining cards. </li>"
                        + "<li> At game start one card is flipped face up, starting the discard pile. </li>"
                        + "<li> Each player reveals 2 cards from their grid. </li>"
                        + "<li> The player with the highest sum from their revealed cards goes frist. </li>"
                        + "</ul>"
                        + "</html>");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextPane1.setText(
                "<html> "
                        + "<h3> Turn Structure </h3>"
                        + "<b> Option 1 - Swap </b>"
                        + "<ul>"
                        + "<li> You can choose to swap any card from your grid with the topmost discard pile card. </li>"
                        + "<li> The card removed from your grid is revealed and placed atop the discard pile. </li>"
                        + "<li> The new card in your grid remains face-up. </li>"
                        + "</ul>"
                        + "<b> Option 2 - Draw </b>"
                        + "<ul>"
                        + "<li> Draw the top card from the deck. </li>"
                        + "<li> Choose one:"
                        + "<ul>"
                        + "<li> Swap the drawn card with a card in your grid. </li>"
                        + "<li> OR discard the drawn card and flip one face-down card in your grid. </li>"
                        + "</ul>"
                        + "</li>"
                        + "</ul>"
                        + "</html>");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jTextPane1.setText(
                "<html> "
                        + "<h3> Hidden Cards </h3>"
                        + "<ul>"
                        + "<li> Face-down cards may never be viewed before replacing them. </li>"
                        + "<li> Once revealed, cards remain face-up. </li>"
                        + "</ul>"
                        + "</html>");  
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jTextPane1.setText(
                "<html> "
                        + "<h3> Column Elimination </h3>"
                        + "<ul>"
                        + "<li> If all three cards in a column have the same value: </li>"
                        + "<ul>"
                        + "<li> Discard all three cards. </li>"
                        + "<li> These three cards go ontop of any other cards discarded in the process. </li>"
                        + "<li> The spaces on your grid become empty, and score 0 points at round end. </li>"
                        + "</ul>"
                        + "</ul>"
                        + "</html>");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextPane1.setText(
                "<html> "
                        + "<h3> End of Round </h3>"
                        + "<ul>"
                        + "<li> The round ends when one player has all their cards face-up, and is \"out\". </li>"
                        + "<li> Every other player gets one more turn after a player goes out. </li>"
                        + "<li> Reveal all remaining face-down cards. </li>"
                        + "<li> Apply any new column eliminations. </li>"
                        + "<li> Score all remaining cards. </li>"
                        + "</ul>"
                        + "</html>");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jTextPane1.setText(
                "<html> "
                        + "<h3> Penalty Rule </h3>"
                        + "<ul>"
                        + "<li> If the player who went out first does <b>not</b> have the lowest score that round, their round score is doubled. </li>"
                        + "<li> If their score was 0 or negative, it is not doubled. </li>"
                        + "</ul>"
                        + "</html>");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jTextPane1.setText(
                "<html> "
                        + "<h3> Scoring </h3>"
                        + "<ul>"
                        + "<li> Sum the values of all remaining cards. </li>"
                        + "<li> Empty spaces are worth 0. </li>"
                        + "<li> This round score is added to your cumulative game score. </li>"
                        + "</ul>"
                        + "</html>");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        jTextPane1.setText(
                "<html> "
                        + "<h3> Game End </h3>"
                        + "<ul>"
                        + "<li> Play rounds until a player reaches 100 or more total points at round end. </li>"
                        + "<li> The player with the lowest cumulative game score wins. </li>"
                        + "</ul>"
                        + "</html>");
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InstructionPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
